"""add tenant provider bindings

Revision ID: 04e2d17e1410
Revises: 0c13113d2290
Create Date: 2026-08-05 17:29:12.980493

"""
from alembic import op
import sqlalchemy as sa


revision = '04e2d17e1410'
down_revision = '0c13113d2290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers_tenant_bindings',
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_providers_tenant_bindings_tenant')
    )
    op.create_index(op.f('ix_providers_tenant_bindings_tenant_id'), 'providers_tenant_bindings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_tenant_bindings_tenant_id'), table_name='providers_tenant_bindings')
    op.drop_table('providers_tenant_bindings')
    # ### end Alembic commands ###
