"""initial schema

Revision ID: f8a4963007ac
Revises: 
Create Date: 2026-07-23 01:37:38.419467

"""
import sqlalchemy as sa
from alembic import op

revision = 'f8a4963007ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_entries',
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_entries_status'), 'accounting_entries', ['status'], unique=False)
    op.create_index(op.f('ix_accounting_entries_tenant_id'), 'accounting_entries', ['tenant_id'], unique=False)
    op.create_table('addresses_records',
    sa.Column('line1', sa.String(length=256), nullable=False),
    sa.Column('line2', sa.String(length=256), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_records_postcode'), 'addresses_records', ['postcode'], unique=False)
    op.create_index(op.f('ix_addresses_records_tenant_id'), 'addresses_records', ['tenant_id'], unique=False)
    op.create_table('admin_persons',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_persons_kind'), 'admin_persons', ['kind'], unique=False)
    op.create_index(op.f('ix_admin_persons_tenant_id'), 'admin_persons', ['tenant_id'], unique=False)
    op.create_table('audit_chain_head',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('head_hmac', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_audit_head_tenant')
    )
    op.create_index(op.f('ix_audit_chain_head_tenant_id'), 'audit_chain_head', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=False),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('prev_hmac', sa.String(length=64), nullable=False),
    sa.Column('hmac', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=32), server_default='k1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'seq', name='uq_audit_tenant_seq')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_hmac'), 'audit_events', ['hmac'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_family_id'), 'billing_invoices', ['family_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_number'), 'billing_invoices', ['number'], unique=False)
    op.create_index(op.f('ix_billing_invoices_status'), 'billing_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_billing_invoices_tenant_id'), 'billing_invoices', ['tenant_id'], unique=False)
    op.create_table('contracts_contracts',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contracts_status'), 'contracts_contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_contracts_tenant_id'), 'contracts_contracts', ['tenant_id'], unique=False)
    op.create_table('dlm_interactions',
    sa.Column('audit_event_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('retrieval_keys', sa.JSON(), nullable=False),
    sa.Column('hmac', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlm_interactions_tenant_id'), 'dlm_interactions', ['tenant_id'], unique=False)
    op.create_table('documents_documents',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_documents_classification'), 'documents_documents', ['classification'], unique=False)
    op.create_index(op.f('ix_documents_documents_status'), 'documents_documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_documents_tenant_id'), 'documents_documents', ['tenant_id'], unique=False)
    op.create_table('expenses_expenses',
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('receipt_document_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expenses_status'), 'expenses_expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_expenses_tenant_id'), 'expenses_expenses', ['tenant_id'], unique=False)
    op.create_table('identity_users',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='member', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_users_email'), 'identity_users', ['email'], unique=True)
    op.create_index(op.f('ix_identity_users_tenant_id'), 'identity_users', ['tenant_id'], unique=False)
    op.create_table('scheduling_schedules',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_schedules_starts_at'), 'scheduling_schedules', ['starts_at'], unique=False)
    op.create_index(op.f('ix_scheduling_schedules_tenant_id'), 'scheduling_schedules', ['tenant_id'], unique=False)
    op.create_table('signup_applications',
    sa.Column('student_name', sa.String(length=256), nullable=False),
    sa.Column('parent_name', sa.String(length=256), nullable=False),
    sa.Column('parent_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_applications_parent_email'), 'signup_applications', ['parent_email'], unique=False)
    op.create_index(op.f('ix_signup_applications_status'), 'signup_applications', ['status'], unique=False)
    op.create_index(op.f('ix_signup_applications_tenant_id'), 'signup_applications', ['tenant_id'], unique=False)
    op.create_table('taxes_filings',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxes_filings_kind'), 'taxes_filings', ['kind'], unique=False)
    op.create_index(op.f('ix_taxes_filings_period_year'), 'taxes_filings', ['period_year'], unique=False)
    op.create_index(op.f('ix_taxes_filings_status'), 'taxes_filings', ['status'], unique=False)
    op.create_index(op.f('ix_taxes_filings_tenant_id'), 'taxes_filings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxes_filings_tenant_id'), table_name='taxes_filings')
    op.drop_index(op.f('ix_taxes_filings_status'), table_name='taxes_filings')
    op.drop_index(op.f('ix_taxes_filings_period_year'), table_name='taxes_filings')
    op.drop_index(op.f('ix_taxes_filings_kind'), table_name='taxes_filings')
    op.drop_table('taxes_filings')
    op.drop_index(op.f('ix_signup_applications_tenant_id'), table_name='signup_applications')
    op.drop_index(op.f('ix_signup_applications_status'), table_name='signup_applications')
    op.drop_index(op.f('ix_signup_applications_parent_email'), table_name='signup_applications')
    op.drop_table('signup_applications')
    op.drop_index(op.f('ix_scheduling_schedules_tenant_id'), table_name='scheduling_schedules')
    op.drop_index(op.f('ix_scheduling_schedules_starts_at'), table_name='scheduling_schedules')
    op.drop_table('scheduling_schedules')
    op.drop_index(op.f('ix_identity_users_tenant_id'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_email'), table_name='identity_users')
    op.drop_table('identity_users')
    op.drop_index(op.f('ix_expenses_expenses_tenant_id'), table_name='expenses_expenses')
    op.drop_index(op.f('ix_expenses_expenses_status'), table_name='expenses_expenses')
    op.drop_table('expenses_expenses')
    op.drop_index(op.f('ix_documents_documents_tenant_id'), table_name='documents_documents')
    op.drop_index(op.f('ix_documents_documents_status'), table_name='documents_documents')
    op.drop_index(op.f('ix_documents_documents_classification'), table_name='documents_documents')
    op.drop_table('documents_documents')
    op.drop_index(op.f('ix_dlm_interactions_tenant_id'), table_name='dlm_interactions')
    op.drop_table('dlm_interactions')
    op.drop_index(op.f('ix_contracts_contracts_tenant_id'), table_name='contracts_contracts')
    op.drop_index(op.f('ix_contracts_contracts_status'), table_name='contracts_contracts')
    op.drop_table('contracts_contracts')
    op.drop_index(op.f('ix_billing_invoices_tenant_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_status'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_number'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_family_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_hmac'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_audit_chain_head_tenant_id'), table_name='audit_chain_head')
    op.drop_table('audit_chain_head')
    op.drop_index(op.f('ix_admin_persons_tenant_id'), table_name='admin_persons')
    op.drop_index(op.f('ix_admin_persons_kind'), table_name='admin_persons')
    op.drop_table('admin_persons')
    op.drop_index(op.f('ix_addresses_records_tenant_id'), table_name='addresses_records')
    op.drop_index(op.f('ix_addresses_records_postcode'), table_name='addresses_records')
    op.drop_table('addresses_records')
    op.drop_index(op.f('ix_accounting_entries_tenant_id'), table_name='accounting_entries')
    op.drop_index(op.f('ix_accounting_entries_status'), table_name='accounting_entries')
    op.drop_table('accounting_entries')
    # ### end Alembic commands ###
